spring:
  application:
    name: sifa-poliklinik
  profiles:
    active: dev

server:
  port: 8080

jwt:
  secret: SifaPoliklinikGizliAnahtari2026CokGucluBirSecretKey123456789!
  expiration: 86400000

poliklinik:
  randevu:
    calisma-baslangic-saati: 9
    calisma-bitis-saati: 17
    ogle-molasi-saati: 12
  muayene:
    varsayilan-ucret: 200.0
